BSS_ITEMS = [
    "Sprinkler",
    "Micro-Converter",
    "Gumdrops",
    "Field Dice",
    "Magic Beans",
    "Stinger",
    "Coconut",
    "Snowflake",
    "Glue",
    "Oil",
    "Tropical Drink",
    "Super Smoothie",
#   "Star Jelly",
#    "Soft Wax",
#    "Hard Wax",
#   "Caustic Wax",
#    "Swirled Wax",
#    "Turpentine",
    "Red Extract",
    "Blue Extract",
    "Enzymes",
#    "Honeysuckle",
]

DEFAULT_HOTBAR = {
    "1": "Sprinkler",
    "2": "Micro-Converter",
    "3": "Gumdrops",
    "4": "Field Dice",
    "5": "Magic Beans",
    "6": "Stinger",
    "7": "Coconut",
}
